ci: smoke test improvements

diff --git a/ci/tasks/smoke-test.yml b/ci/tasks/smoke-test.yml
--- a/ci/tasks/smoke-test.yml
+++ b/ci/tasks/smoke-test.yml
@@ -16,7 +16,7 @@ run:
     - -c
     - |
       test_for_substring () {
-        grep -F "$1" "$2" > /dev/null && echo "Found substring $1"
+        grep -F "$1" "$2" > /dev/null || (echo "Missing substring $1" && false)
       }
 
       export API_BASE_URL=$(jq -r '.api_base_url.value' terraform-outputs/outputs.json)
@@ -36,10 +36,26 @@ run:
       echo "Probing $TARGET_URL"
       curl $TARGET_URL -f > jwks.json
       jq -e '(.keys | length) >= 1' jwks.json > /dev/null \
-        && echo "Found populated 'keys' array"
+        || (echo "Missing populated 'keys' array" && false)
 
       export TARGET_URL="$API_BASE_URL/.well-known/openid-configuration"
       echo "Probing $TARGET_URL"
       curl $TARGET_URL -f > openid-configuration.json
       jq -e '.issuer == env.API_BASE_URL' openid-configuration.json > /dev/null \
-        && echo "Found correct 'issuer'"
+        || (echo "Missing correct 'issuer'" && false)
+      jq -e '.claims_supported | contains(["https://aws.amazon.com/tags"])' openid-configuration.json > /dev/null \
+        || (echo "Missing session tags in 'claims_supported'" && false)
+
+      export TARGET_URL="$API_BASE_URL/token"
+      echo "Probing $TARGET_URL"
+      export TOKEN_STATUS_CODE=$(
+        curl $TARGET_URL -XPOST \
+          -d "client_id=$GITHUB_CLIENT_ID" \
+          -d "code=12341234" \
+          -d "state=$RANDOM" \
+          -o /dev/stderr \
+          --write-out '%{http_code}'
+      )
+      [ "$TOKEN_STATUS_CODE" == '400' ] || (
+        echo "Expected 400 status code, got '$TOKEN_STATUS_CODE'" && false
+      )
